version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: deliveru_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: deliveru
      POSTGRES_PASSWORD: deliveru_dev
      POSTGRES_DB: deliveru
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
